# Generated by Django 5.1 on 2024-08-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
